### ISSUE TITLE
Escape closes application without warning

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#14]
### Steps to reproduce
1. Start a game
2. Hit Esc

### Suggested Fix
This should be either completely prevented or there should at the least be a warning dialog.

**Comment by ThePenguin1140** [comment]
Right now there's no way to get back to the main menu when in game. Maybe mapping the ESC to take you there would work.

**Comment by aarontabor** [comment]
I'm a little hesitant to make the ESC key take the player back to the main menu without warning. I propose doing the following:

- both SPACE and ESC key pauses the game
- add a button to the pause screen to quit the current game

**Comment by aarontabor** [comment]
Currently implemented on `feature/escape_key`:

- escape no longer closes application without warning
- escape key pauses game during game play
- the user is now prompted to confirm before exit when they click MainMenu::Exit.

Before I implement the pause-screen quit button, just wondering what you guys think. Since the pause screen is shared with the Settings::IO_Settings screen, it might be a little tricky to get right. I'll move on to something else for now and we can decide if the quit button is worth it.

**Comment by aarontabor** [comment]
Would be nice to have a "Exit to Main Menu" button on pause menu, but I'm going to raise the concern in a new issue and close this off.

**Comment by aarontabor** [comment]
Addressed in 526911010ab67dfb5dfddc8aa16db09f0676643f, c05c191adec40d7851f6a933aafa7ab624131757, and 515a6159236a2e308d91d7f2ab4829c1de7f9e74
