### ISSUE TITLE
Coin spawn causes a small stutter in the game animations

### ISSUE THREAD

**Issue by ThePenguin1140** [hcilab/processing-games#24]
When a coin spawns the game animations often stutter. This includes the platforms moving up, but it's most noticable if you accelerate the character to a decent speed. Then it'll stop for a second and then continue flying. 

Moving around really fast, especially while in the air does seem kind of laggy/choppy. This might be an underlying problem related to how we add and remove things from the game state.

**Comment by ThePenguin1140** [comment]
This might be related to #4

**Comment by ThePenguin1140** [comment]
Can confirm, platforms spawning at the bottom also cause a stutter.

**Comment by ThePenguin1140** [comment]
## Suggested solution

Spawn coins below the bottom of the screen therefore making the jumps undetectable to the user.

**Comment by aarontabor** [comment]
Coins now only spawn on platforms below the bottom of the screen on `feature/coin_spawn`. However, the reduced window where coin spawn is possible means that fewer coins will be spawned overall (especially on higher levels). We have several options:
- spawn coins more frequently (i.e., lots of coins on lower levels, some coins on higher levels)
- spawn platforms even lower (i.e., way, way below the bottom of the screen, so that coins have a longer time to accumulate)
- introduce a more complex coin spawning algorithm (i.e., takes level/platform speed into consideration)

**Comment by aarontabor** [comment]
I'm moving this question to issue #38

**Comment by aarontabor** [comment]
Closed by 19152b5f61e5392fea4a28c37f1f190d84ef98d8

**Comment by ThePenguin1140** [comment]
I think https://github.com/hcilab/processing-games/commit/19152b5f61e5392fea4a28c37f1f190d84ef98d8 closes #4 instead of this one?

**Comment by aarontabor** [comment]
This issue will be resolved by getting to the root of the "stutter" problem and fixing. We are currently working around this issue for coins like Jason said in #4.

**Comment by alex959595** [comment]
Non-issue with coin spawning off-screen
