### ISSUE TITLE
Increase coin spawn rate

### ISSUE THREAD

**Issue by AlexKienzle** [hcilab/processing-games#38]
I just got to level 99 (using the Myo) and I only got 7 coins in the ~8.5 minutes I survived. I should have been drowning in cash at that point. The suggested solution to #24 (coins spawn at bottom) may help this as well.

![highscore](https://cloud.githubusercontent.com/assets/19151434/15539146/23e61f70-2257-11e6-9e81-6dff293730e6.png)

**Comment by AlexKienzle** [comment]
Maybe spawn rate should be level-based, you mostly see coins at earlier levels because it is slower. At level 99 you should see tons of coins, but it is rare to see any.

**Comment by aarontabor** [comment]
We have several options:
- spawn coins more frequently (i.e., lots of coins on lower levels, some coins on higher levels)
- spawn platforms even lower (i.e., way, way below the bottom of the screen, so that coins have a longer time to accumulate)
- introduce a more complex coin spawning algorithm (i.e., takes level/platform speed into consideration)

**Comment by aarontabor** [comment]
I'm going to introduce a coin spawning algorithm that considers the current level. More coins will be spawned at higher levels.
